import '../models/vocabulary_model.dart';

/// Full-stack and AI focused vocabulary data
class VocabularyData {
  static List<VocabularyWord> get allWords => [
        // FRONTEND DEVELOPMENT
        VocabularyWord(
          id: 'fe_001',
          english: 'component',
          indonesian: 'komponen',
          pronunciation: '/kəmˈpoʊ.nənt/',
          category: 'frontend',
          exampleSentence: 'This React component handles user authentication',
          exampleSentenceIndonesian: 'Komponen React ini menangani autentikasi pengguna',
          synonyms: ['module', 'element', 'part'],
          relatedWords: ['props', 'state', 'render'],
        ),
        VocabularyWord(
          id: 'fe_002',
          english: 'render',
          indonesian: 'merender/menampilkan',
          pronunciation: '/ˈren.dɚ/',
          category: 'frontend',
          exampleSentence: 'The app renders the homepage in under 100ms',
          exampleSentenceIndonesian: 'Aplikasi merender halaman utama dalam kurang dari 100ms',
          synonyms: ['display', 'draw', 'generate'],
          relatedWords: ['component', 'DOM', 'virtual DOM'],
        ),
        VocabularyWord(
          id: 'fe_003',
          english: 'state',
          indonesian: 'state/keadaan',
          pronunciation: '/steɪt/',
          category: 'frontend',
          exampleSentence: 'We manage global state with Redux',
          exampleSentenceIndonesian: 'Kami mengelola state global dengan Redux',
          synonyms: ['condition', 'status', 'data'],
          relatedWords: ['props', 'context', 'store'],
        ),
        VocabularyWord(
          id: 'fe_004',
          english: 'props',
          indonesian: 'props/properti',
          pronunciation: '/prɒps/',
          category: 'frontend',
          exampleSentence: 'Pass the user data as props to the child component',
          exampleSentenceIndonesian: 'Teruskan data pengguna sebagai props ke komponen anak',
          synonyms: ['properties', 'attributes', 'parameters'],
          relatedWords: ['component', 'state', 'callback'],
        ),
        VocabularyWord(
          id: 'fe_005',
          english: 'hook',
          indonesian: 'hook',
          pronunciation: '/hʊk/',
          category: 'frontend',
          exampleSentence: 'UseEffect hook handles side effects in functional components',
          exampleSentenceIndonesian: 'Hook useEffect menangani efek samping dalam komponen fungsional',
          synonyms: ['function', 'utility'],
          relatedWords: ['useState', 'useEffect', 'useContext'],
        ),
        VocabularyWord(
          id: 'fe_006',
          english: 'responsive',
          indonesian: 'responsif',
          pronunciation: '/rɪˈspɒn.sɪv/',
          category: 'frontend',
          exampleSentence: 'The design is fully responsive on all devices',
          exampleSentenceIndonesian: 'Desainnya sepenuhnya responsif di semua perangkat',
          synonyms: ['adaptive', 'flexible'],
          relatedWords: ['breakpoint', 'media query', 'mobile-first'],
        ),

        // BACKEND DEVELOPMENT
        VocabularyWord(
          id: 'be_001',
          english: 'endpoint',
          indonesian: 'endpoint',
          pronunciation: '/ˈend.pɔɪnt/',
          category: 'backend',
          exampleSentence: 'The /api/users endpoint returns a list of users',
          exampleSentenceIndonesian: 'Endpoint /api/users mengembalikan daftar pengguna',
          synonyms: ['route', 'URL', 'path'],
          relatedWords: ['API', 'request', 'response'],
        ),
        VocabularyWord(
          id: 'be_002',
          english: 'middleware',
          indonesian: 'middleware',
          pronunciation: '/ˈmɪd.l̩.wer/',
          category: 'backend',
          exampleSentence: 'Authentication middleware validates tokens before processing requests',
          exampleSentenceIndonesian: 'Middleware autentikasi memvalidasi token sebelum memproses permintaan',
          synonyms: ['interceptor', 'filter', 'handler'],
          relatedWords: ['request', 'response', 'pipeline'],
        ),
        VocabularyWord(
          id: 'be_003',
          english: 'authentication',
          indonesian: 'autentikasi',
          pronunciation: '/ɔːˌθen.tɪˈkeɪ.ʃən/',
          category: 'backend',
          exampleSentence: 'JWT authentication secures our API endpoints',
          exampleSentenceIndonesian: 'Autentikasi JWT mengamankan endpoint API kami',
          synonyms: ['verification', 'validation', 'login'],
          relatedWords: ['authorization', 'token', 'session'],
        ),
        VocabularyWord(
          id: 'be_004',
          english: 'authorization',
          indonesian: 'otorisasi',
          pronunciation: '/ɔːˌθɔː.rɪˈzeɪ.ʃən/',
          category: 'backend',
          exampleSentence: 'Authorization checks if the user has permission to access the resource',
          exampleSentenceIndonesian: 'Otorisasi memeriksa apakah pengguna memiliki izin untuk mengakses sumber daya',
          synonyms: ['permission', 'access control'],
          relatedWords: ['authentication', 'role', 'policy'],
        ),
        VocabularyWord(
          id: 'be_005',
          english: 'payload',
          indonesian: 'payload/isian',
          pronunciation: '/ˈpeɪ.loʊd/',
          category: 'backend',
          exampleSentence: 'The request payload contains the user registration data',
          exampleSentenceIndonesian: 'Payload permintaan berisi data pendaftaran pengguna',
          synonyms: ['body', 'data', 'content'],
          relatedWords: ['request', 'response', 'JSON'],
        ),
        VocabularyWord(
          id: 'be_006',
          english: 'deployment',
          indonesian: 'deployment/penyebaran',
          pronunciation: '/dɪˈplɔɪ.mənt/',
          category: 'backend',
          exampleSentence: 'The deployment pipeline automatically tests and releases code',
          exampleSentenceIndonesian: 'Pipeline deployment secara otomatis menguji dan merilis kode',
          synonyms: ['release', 'launch', 'rollout'],
          relatedWords: ['CI/CD', 'production', 'staging'],
        ),

        // AI / MACHINE LEARNING
        VocabularyWord(
          id: 'ai_001',
          english: 'model',
          indonesian: 'model',
          pronunciation: '/ˈmɒd.l̩/',
          category: 'ai',
          exampleSentence: 'We trained the model on 1 million text samples',
          exampleSentenceIndonesian: 'Kami melatih model pada 1 juta sampel teks',
          synonyms: ['algorithm', 'network', 'system'],
          relatedWords: ['training', 'inference', 'weights'],
        ),
        VocabularyWord(
          id: 'ai_002',
          english: 'inference',
          indonesian: 'inferensi',
          pronunciation: '/ˈɪn.fər.əns/',
          category: 'ai',
          exampleSentence: 'The inference API processes requests in real-time',
          exampleSentenceIndonesian: 'API inferensi memproses permintaan secara real-time',
          synonyms: ['prediction', 'processing'],
          relatedWords: ['model', 'latency', 'throughput'],
        ),
        VocabularyWord(
          id: 'ai_003',
          english: 'token',
          indonesian: 'token',
          pronunciation: '/ˈtoʊ.kən/',
          category: 'ai',
          exampleSentence: 'The LLM processes text one token at a time',
          exampleSentenceIndonesian: 'LLM memproses teks satu token pada satu waktu',
          synonyms: ['unit', 'segment'],
          relatedWords: ['embedding', 'vocabulary', 'sequence'],
        ),
        VocabularyWord(
          id: 'ai_004',
          english: 'embedding',
          indonesian: 'embedding/penyematan',
          pronunciation: '/ɛmˈbɛd.ɪŋ/',
          category: 'ai',
          exampleSentence: 'Word embeddings capture semantic relationships',
          exampleSentenceIndonesian: 'Embedding kata menangkap hubungan semantik',
          synonyms: ['vector', 'representation'],
          relatedWords: ['dimension', 'similarity', 'vector space'],
        ),
        VocabularyWord(
          id: 'ai_005',
          english: 'fine-tuning',
          indonesian: 'fine-tuning/penyetelan halus',
          pronunciation: '/ˈfaɪn ˈtuː.nɪŋ/',
          category: 'ai',
          exampleSentence: 'Fine-tuning the model on domain data improves accuracy',
          exampleSentenceIndonesian: 'Fine-tuning model pada data domain meningkatkan akurasi',
          synonyms: ['adjustment', 'optimization', 'customization'],
          relatedWords: ['training', 'weights', 'learning rate'],
        ),
        VocabularyWord(
          id: 'ai_006',
          english: 'prompt',
          indonesian: 'prompt/perintah',
          pronunciation: '/prɒmpt/',
          category: 'ai',
          exampleSentence: 'Write a clear prompt to get better results from the AI',
          exampleSentenceIndonesian: 'Tulis prompt yang jelas untuk mendapatkan hasil lebih baik dari AI',
          synonyms: ['input', 'query', 'instruction'],
          relatedWords: ['completion', 'context', 'temperature'],
        ),
        VocabularyWord(
          id: 'ai_007',
          english: 'LLM',
          indonesian: 'LLM (Large Language Model)',
          pronunciation: '/ˌɛl ˌɛl ˈɛm/',
          category: 'ai',
          exampleSentence: 'LLMs can generate human-like text responses',
          exampleSentenceIndonesian: 'LLM dapat menghasilkan respons teks seperti manusia',
          synonyms: ['language model', 'foundation model'],
          relatedWords: ['transformer', 'GPT', 'parameters'],
        ),
        VocabularyWord(
          id: 'ai_008',
          english: 'RAG',
          indonesian: 'RAG (Retrieval-Augmented Generation)',
          pronunciation: '/ræɡ/',
          category: 'ai',
          exampleSentence: 'RAG combines retrieval with generation for more accurate responses',
          exampleSentenceIndonesian: 'RAG menggabungkan retrieval dengan generation untuk respons yang lebih akurat',
          synonyms: ['hybrid AI', 'retrieval system'],
          relatedWords: ['vector database', 'embedding', 'context'],
        ),

        // DATABASE
        VocabularyWord(
          id: 'db_001',
          english: 'query',
          indonesian: 'query/kueri',
          pronunciation: '/ˈkwɪr.i/',
          category: 'database',
          exampleSentence: 'Optimize the query to reduce database load',
          exampleSentenceIndonesian: 'Optimalkan query untuk mengurangi beban database',
          synonyms: ['request', 'search', 'command'],
          relatedWords: ['SQL', 'index', 'table'],
        ),
        VocabularyWord(
          id: 'db_002',
          english: 'index',
          indonesian: 'index/indeks',
          pronunciation: '/ˈɪn.dɛks/',
          category: 'database',
          exampleSentence: 'Add an index on the user_id column for faster lookups',
          exampleSentenceIndonesian: 'Tambahkan indeks pada kolom user_id untuk pencarian lebih cepat',
          synonyms: ['lookup table', 'reference'],
          relatedWords: ['primary key', 'foreign key', 'performance'],
        ),
        VocabularyWord(
          id: 'db_003',
          english: 'transaction',
          indonesian: 'transaksi',
          pronunciation: '/trænˈzæk.ʃən/',
          category: 'database',
          exampleSentence: 'The transaction ensures all operations complete or none do',
          exampleSentenceIndonesian: 'Transaksi memastikan semua operasi selesai atau tidak ada yang selesai',
          synonyms: ['operation', 'process'],
          relatedWords: ['commit', 'rollback', 'ACID'],
        ),
        VocabularyWord(
          id: 'db_004',
          english: 'schema',
          indonesian: 'schema/skema',
          pronunciation: '/ˈskiː.mə/',
          category: 'database',
          exampleSentence: 'The database schema defines the table structure',
          exampleSentenceIndonesian: 'Schema database mendefinisikan struktur tabel',
          synonyms: ['structure', 'blueprint', 'design'],
          relatedWords: ['table', 'column', 'relationship'],
        ),

        // DEVOPS & CLOUD
        VocabularyWord(
          id: 'dv_001',
          english: 'container',
          indonesian: 'container/wadah',
          pronunciation: '/kənˈteɪ.nɚ/',
          category: 'devops',
          exampleSentence: 'Docker containers package applications with their dependencies',
          exampleSentenceIndonesian: 'Container Docker mengemas aplikasi dengan dependensinya',
          synonyms: ['package', 'environment'],
          relatedWords: ['Docker', 'Kubernetes', 'image'],
        ),
        VocabularyWord(
          id: 'dv_002',
          english: 'orchestration',
          indonesian: 'orchestration/orkestrasi',
          pronunciation: '/ˌɔːr.kɪˈstreɪ.ʃən/',
          category: 'devops',
          exampleSentence: 'Kubernetes handles container orchestration at scale',
          exampleSentenceIndonesian: 'Kubernetes menangani orkestrasi container dalam skala besar',
          synonyms: ['management', 'coordination', 'automation'],
          relatedWords: ['Kubernetes', 'deployment', 'scaling'],
        ),
        VocabularyWord(
          id: 'dv_003',
          english: 'pipeline',
          indonesian: 'pipeline/pipa',
          pronunciation: '/ˈpaɪp.laɪn/',
          category: 'devops',
          exampleSentence: 'The CI/CD pipeline runs tests on every commit',
          exampleSentenceIndonesian: 'Pipeline CI/CD menjalankan tes pada setiap commit',
          synonyms: ['workflow', 'process', 'chain'],
          relatedWords: ['CI/CD', 'automation', 'deployment'],
        ),
        VocabularyWord(
          id: 'dv_004',
          english: 'scalability',
          indonesian: 'skalabilitas',
          pronunciation: '/ˌskeɪ.ləˈbɪl.ɪ.ti/',
          category: 'devops',
          exampleSentence: 'Horizontal scalability allows adding more servers under load',
          exampleSentenceIndonesian: 'Skalabilitas horizontal memungkinkan penambahan lebih banyak server di bawah beban',
          synonyms: ['elasticity', 'expandability'],
          relatedWords: ['load balancing', 'auto-scaling', 'capacity'],
        ),

        // API & INTEGRATION
        VocabularyWord(
          id: 'api_001',
          english: 'REST',
          indonesian: 'REST',
          pronunciation: '/rɛst/',
          category: 'api',
          exampleSentence: 'REST APIs use HTTP methods for CRUD operations',
          exampleSentenceIndonesian: 'API REST menggunakan metode HTTP untuk operasi CRUD',
          synonyms: ['RESTful API', 'web service'],
          relatedWords: ['HTTP', 'JSON', 'endpoint'],
        ),
        VocabularyWord(
          id: 'api_002',
          english: 'GraphQL',
          indonesian: 'GraphQL',
          pronunciation: '/ˈɡræf.kjuː.ɛl/',
          category: 'api',
          exampleSentence: 'GraphQL allows clients to request exactly the data they need',
          exampleSentenceIndonesian: 'GraphQL memungkinkan klien meminta data yang mereka butuhkan',
          synonyms: ['query language', 'API specification'],
          relatedWords: ['query', 'mutation', 'schema'],
        ),
        VocabularyWord(
          id: 'api_003',
          english: 'webhook',
          indonesian: 'webhook',
          pronunciation: '/ˈwɛb.hʊk/',
          category: 'api',
          exampleSentence: 'Configure a webhook to receive real-time notifications',
          exampleSentenceIndonesian: 'Konfigurasi webhook untuk menerima notifikasi real-time',
          synonyms: ['callback', 'reverse API'],
          relatedWords: ['event', 'trigger', 'notification'],
        ),
        VocabularyWord(
          id: 'api_004',
          english: 'latency',
          indonesian: 'latency/latensi',
          pronunciation: '/ˈleɪ.tən.si/',
          category: 'api',
          exampleSentence: 'High latency affects user experience significantly',
          exampleSentenceIndonesian: 'Latensi tinggi mempengaruhi pengalaman pengguna secara signifikan',
          synonyms: ['delay', 'response time'],
          relatedWords: ['throughput', 'bandwidth', 'performance'],
        ),

        // DAILY CONVERSATION
        VocabularyWord(
          id: 'dc_001',
          english: 'standup',
          indonesian: 'standup/rapat berdiri',
          pronunciation: '/ˈstænd.ʌp/',
          category: 'daily',
          exampleSentence: 'What did you work on in yesterday\'s standup?',
          exampleSentenceIndonesian: 'Apa yang kamu kerjakan di standup kemarin?',
          synonyms: ['daily meeting', 'scrum'],
          relatedWords: ['sprint', 'blocker', 'update'],
        ),
        VocabularyWord(
          id: 'dc_002',
          english: 'blocker',
          indonesian: 'blocker/hambatan',
          pronunciation: '/ˈblɒ.kɚ/',
          category: 'daily',
          exampleSentence: 'I have a blocker with the API integration',
          exampleSentenceIndonesian: 'Saya memiliki hambatan dengan integrasi API',
          synonyms: ['obstacle', 'impediment', 'issue'],
          relatedWords: ['unblock', 'help', 'dependency'],
        ),
        VocabularyWord(
          id: 'dc_003',
          english: 'deadline',
          indonesian: 'deadline/tenggat waktu',
          pronunciation: '/ˈdɛd.laɪn/',
          category: 'daily',
          exampleSentence: 'The deadline for this feature is Friday',
          exampleSentenceIndonesian: 'Deadline untuk fitur ini adalah hari Jumat',
          synonyms: ['due date', 'cutoff', 'target date'],
          relatedWords: ['sprint', 'milestone', 'delivery'],
        ),
        VocabularyWord(
          id: 'dc_004',
          english: 'PR',
          indonesian: 'PR (Pull Request)',
          pronunciation: '/ˌpiː ˈɑːr/',
          category: 'daily',
          exampleSentence: 'Can you review my PR when you have time?',
          exampleSentenceIndonesian: 'Bisakah kamu mereview PR saya ketika ada waktu?',
          synonyms: ['merge request', 'code review'],
          relatedWords: ['review', 'merge', 'branch'],
        ),
        VocabularyWord(
          id: 'dc_005',
          english: 'deploy',
          indonesian: 'deploy/menerapkan',
          pronunciation: '/dɪˈplɔɪ/',
          category: 'daily',
          exampleSentence: 'We deploy to production every Tuesday',
          exampleSentenceIndonesian: 'Kami deploy ke production setiap hari Selasa',
          synonyms: ['release', 'launch', 'push'],
          relatedWords: ['production', 'staging', 'rollback'],
        ),

        // BUSINESS ENGLISH
        VocabularyWord(
          id: 'bs_001',
          english: 'stakeholder',
          indonesian: 'stakeholder/pemangku kepentingan',
          pronunciation: '/ˈsteɪk.hoʊl.dɚ/',
          category: 'business',
          exampleSentence: 'We need to present the roadmap to stakeholders',
          exampleSentenceIndonesian: 'Kami perlu mempresentasikan roadmap kepada stakeholder',
          synonyms: ['interested party', 'client', 'investor'],
          relatedWords: ['requirement', 'expectation', 'feedback'],
        ),
        VocabularyWord(
          id: 'bs_002',
          english: 'roadmap',
          indonesian: 'roadmap/peta jalan',
          pronunciation: '/ˈroʊd.mæp/',
          category: 'business',
          exampleSentence: 'The product roadmap shows features for the next quarter',
          exampleSentenceIndonesian: 'Roadmap produk menampilkan fitur untuk kuartal berikutnya',
          synonyms: ['plan', 'timeline', 'strategy'],
          relatedWords: ['milestone', 'quarter', 'goal'],
        ),
        VocabularyWord(
          id: 'bs_003',
          english: 'deliverable',
          indonesian: 'deliverable/hasil kerja',
          pronunciation: '/dɪˈlɪv.ɚ.ə.bəl/',
          category: 'business',
          exampleSentence: 'The main deliverable is a working prototype',
          exampleSentenceIndonesian: 'Deliverable utama adalah prototipe yang berfungsi',
          synonyms: ['output', 'result', 'product'],
          relatedWords: ['milestone', 'deadline', 'requirement'],
        ),
        VocabularyWord(
          id: 'bs_004',
          english: 'alignment',
          indonesian: 'alignment/penyelarasan',
          pronunciation: '/əˈlaɪn.mənt/',
          category: 'business',
          exampleSentence: 'Let\'s schedule a meeting for alignment on the requirements',
          exampleSentenceIndonesian: 'Mari jadwalkan rapat untuk alignment tentang persyaratan',
          synonyms: ['agreement', 'consensus', 'harmony'],
          relatedWords: ['sync', 'collaboration', 'understanding'],
        ),
      ];

  /// Get words by category
  static List<VocabularyWord> getByCategory(String category) {
    return allWords.where((w) => w.category == category).toList();
  }

  /// Get all unique categories
  static List<String> get categories {
    return allWords.map((w) => w.category).toSet().toList();
  }

  /// Search words by English or Indonesian term
  static List<VocabularyWord> search(String query) {
    final lowerQuery = query.toLowerCase();
    return allWords
        .where((w) =>
            w.english.toLowerCase().contains(lowerQuery) ||
            w.indonesian.toLowerCase().contains(lowerQuery))
        .toList();
  }
}
